name: Lint Entity API

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "api/**"
      - "!api/deploy/**"

defaults:
  run:
    working-directory: api

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Upgrade pip and setuptools
        run: pip install --upgrade pip setuptools
      - name: Install test requirements
        run: pip install -e .[dev]
      - name: Mypy type check
        run: mypy entityapi/
      - name: Black syntax check
        run: black --check entityapi/
